GET http://localhost:3003/api/blogs

### add person
POST http://localhost:3003/api/blogs/ HTTP/3
content-type: application/json

{
  "title": "test",
  "author": "VC",
  "url": "vc.com",
  "likes": 101
}