GET http://localhost:3003/api/blogs

### 
POST http://localhost:3003/api/blogs/ HTTP/3
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZjY2MiLCJpZCI6IjYzYWNhNTJlZDAxY2QzZGFiYWQxY2Y0NiIsImlhdCI6MTY3NTA2OTA2MCwiZXhwIjoxNjc1MDcyNjYwfQ.6w0r-lxOM0oWBSb33cUELx3Hs0xIVCTDJUIxSEI1wDs

{
  "title": "sample blog",
  "author": "sampleUser",
  "url": "http://sampleBlog.com",
  "likes": 111  
}

### modify likes
PUT http://localhost:3003/api/blogs/63d0d8e4070db107cc2323a9
Content-Type: application/json

{
  "likes": 9
}

### delete blog
DELETE http://localhost:3003/api/blogs/63d27367c788cf562feb174a
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZjY2MiLCJpZCI6IjYzYWNhNTJlZDAxY2QzZGFiYWQxY2Y0NiIsImlhdCI6MTY3NTA2OTA2MCwiZXhwIjoxNjc1MDcyNjYwfQ.6w0r-lxOM0oWBSb33cUELx3Hs0xIVCTDJUIxSEI1wDs

### add comment
POST http://localhost:3003/api/blogs/63d7a73aedabfc8c649faf7d/comments
content-type: application/json

{
  "comment": "never gonna let you down"
}